language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r ./flightpath/requirements.txt"
# command to run tests
script: "coverage run --source=flightpath -m unittest discover -v"
after_success:
  - coveralls
